#include "api.h"
#include <stdio.h>
#include <string.h>
int op_extended_colormap_count;void *op_extended_colormaps[128];static int checks,failures,calls,mode;static void *seen[8];static unsigned char a,b,c,d,e,sentinels[128];
static void check(int x,const char*s){++checks;if(!x){++failures;printf("FAIL: %s\n",s);}}
void op_rd_colormap_free(void *p){if(calls>=0&&calls<8)seen[calls]=p;else check(0,"seen bound");++calls;if(mode==1&&calls==1)op_extended_colormap_count=1;if(mode==2&&calls==1){op_extended_colormap_count=3;op_extended_colormaps[1]=&d;op_extended_colormaps[2]=&e;}}
static void fill(void){int i;for(i=0;i<128;++i)op_extended_colormaps[i]=&sentinels[i];}
static void guarded(int count){void *before[128];fill();memcpy(before,op_extended_colormaps,sizeof(before));op_extended_colormap_count=count;calls=0;mode=0;op_extended_free_colormaps();check(calls==0,"nonpositive count no calls");check(op_extended_colormap_count==0,"nonpositive resets count");check(memcmp(before,op_extended_colormaps,sizeof(before))==0,"nonpositive preserves array");}
int main(void){void *before[128];fill();op_extended_colormaps[0]=&a;op_extended_colormaps[1]=0;op_extended_colormaps[2]=&c;memcpy(before,op_extended_colormaps,sizeof(before));op_extended_colormap_count=3;calls=0;mode=0;op_extended_free_colormaps();check(calls==3&&seen[0]==&a&&seen[1]==0&&seen[2]==&c,"ordered entries including null");check(op_extended_colormap_count==0,"ordinary reset");check(memcmp(before,op_extended_colormaps,sizeof(before))==0,"slots retained");fill();op_extended_colormaps[0]=&a;op_extended_colormaps[1]=&b;memcpy(before,op_extended_colormaps,sizeof(before));op_extended_colormap_count=3;calls=0;mode=1;op_extended_free_colormaps();check(calls==1,"live reduced count stops loop");check(op_extended_colormap_count==0,"reduced count final reset");check(seen[0]==&a,"reduced count argument");check(memcmp(before,op_extended_colormaps,sizeof(before))==0,"reduced count preserves all slots");fill();op_extended_colormaps[0]=&a;memcpy(before,op_extended_colormaps,sizeof(before));before[1]=&d;before[2]=&e;op_extended_colormap_count=1;calls=0;mode=2;op_extended_free_colormaps();check(calls==3&&seen[0]==&a&&seen[1]==&d&&seen[2]==&e,"live expansion and replaced slots");check(op_extended_colormap_count==0,"expanded count final reset");check(memcmp(before,op_extended_colormaps,sizeof(before))==0,"expanded count retains only callback slot mutations");guarded(0);guarded(-3);printf("Extended free colormaps: %d checks, %d failures\n",checks,failures);return failures!=0;}
